补充修正了一些表面界面的翻译
sfire/bl_ui_hanzify pull request #2
Opened 2019-04-21 14:56 UTC by millionart

补充修正了一些表面界面的翻译
修正了几处小的用词习惯
规范了几处中英文混排空格

2019-04-23 16:41 UTC, sfire requested changes
感谢贡献词条译文，多数的修改都是很好的。但也存在一些问题，总结一下，主要以下几个方面：

1. 描边并不能准确描述 `Freestyle`，而且之前的UI和手册一直是使用英文的，贸然改动，老用户反而不适应，请保留 `Freestyle`

2. `sletection` 与 `selected` 在tooltip中改为 `选中的` ，这我不反对。但是，在菜单中，为了简洁起见，建议保留 `所选`，这个词本身也没有歧义。(未一一标记，请对照UI更正)

3. `link` 在Blender中一直译为 `关联`，请保留

4. 多处词条更正后，fuzzy状态未取消

5. `msgid ""` 为原文词条，请不要改词条原文。

其余小问题，也有标记，请更正后重新提交。^-^

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "描边风格模块"
Freestyle保留英文吧，一直用的freestyle，改个名字大家不一定适应。

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "描边风格设置"
同上，freestyle需保留英文。

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "描边风格线条样式"
同上，`freestyle` 需保留英文。

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "描边风格线条样式, 可供多个样式集重复使用"
同上，`freestyle` 需保留英文。

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "返回"
此处的 `Return` 是指Mac上的回车键，并非返回之意。

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "描边风格标记边"
同上，`freestyle` 需保留英文。

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "描边风格标记"
同上，`freestyle` 需保留英文。

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "查看选中的"
tooltip里 `selected` 改为 `选中的` 我不反对，但是菜单里还是保留 `所选` ，简洁为好

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "删除选中的骨骼"
同上，建议保留 `所选`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "删除选中的骨骼"
同上，建议保留 `所选`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "复制选中的骨骼"
同上，建议保留 `所选`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "从所有未链接的集合中删除"
Blender手册与UI中 `link` 一直译为 `关联`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "移动选中的"
同上，建议保留 `所选`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
>  #, fuzzy
fuzzy状态记得取消

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "将游标吸附到选中的项"
同上，建议保留 `所选`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
>  #, fuzzy
同上，fuzzy 状态未取消

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "将选中的项吸附到游标"
同上，建议保留 `所选`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "将选中的项吸附到栅格点"
同上，建议保留 `所选`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
>  #, fuzzy
同上，fuzzy状态未取消

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "描边风格边标记"
请保留 `freestyle`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "描边风格面标记"
请保留 `freestyle`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "链接到集合"
`link` 应译为 `关联`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
>  #, fuzzy
fuzzy状态未取消

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
>  #, fuzzy
fuzzy状态未取消

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "为选中的添加驱动"
同上，建议保留 `所选`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "删除选中的的驱动"
同上，建议保留 `所选`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
>  #, fuzzy
fuzzy状态未取消

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "插帧集选项中添加选中的"
同上，建议保留 `所选`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "插帧集选项中移除选中的"
同上，建议保留 `所选`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "将约束复制到当前选中的骨骼"
同上，建议保留 `所选`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "将选中的项添加到骨骼组"
同上，建议保留 `所选`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "从骨骼组中删除选中的"
同上，建议保留 `所选`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "只考虑选中的部分"
同上，建议保留 `所选`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "恢复选中的骨骼的位置为默认值"
同上，建议保留 `所选`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "移除选中的骨骼的所有 IK 约束"
同上，建议保留 `所选`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
>  #, fuzzy
fuzzy状态未取消

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
>  #, fuzzy
fuzzy状态未取消

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
>  #, fuzzy
fuzzy状态未取消

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
>  #, fuzzy
fuzzy状态未取消

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "描边风格线条集"
请保留 `freestyle`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "描边风格"
请保留 `freestyle`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "游标表面项目"
我没对照 UI看，但是此处 `project` 可能是 `投射` 或 `投影` 之意，请再确认一下

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "中央处理器"
直接用CPU可能更通俗一些

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "统一计算架构"
CUDA也一样，建议保留英文缩写。

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "环境光遮蔽采样"
AO建议保留缩写形式。

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgid "外观显影预览"
不要改词条原文

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgid "显示外观显影球和调色板"
不要改词条原文

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "全不"
这个词条语境比较多，保留为 ` 无` 吧

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "清除描边风格边"
请保留 `freestyle`

2019-04-23 16:41 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "清除描边风格面"
请保留 `freestyle`

2019-04-23 16:57 UTC, sfire requested changes
大体的问题与前一次review差不多，另外 `lookdev` 的译法需与社区再作讨论，先暂时保留一下。

2019-04-23 16:57 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "选中的物体 -> 活动物体"
`sletection` 与 `selected` 在tooltip中改为 `选中的` ，这我不反对。但是，在菜单中，为了简洁起见，建议保留 `所选`

2019-04-23 16:57 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "使用 '选中的物体 -> 活动物体' 时的内侧光线投射距离"
此处建议与菜单统一为 `所选`

2019-04-23 16:57 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "描边风格线条集"
描边并不能准确描述 `Freestyle`，而且之前的UI和手册一直是使用英文的，贸然改动，老用户反而不适应，请保留 `Freestyle`

2019-04-23 16:57 UTC, sfire commented on zh_CN/zh_CN.po
>  #, fuzzy
fuzzy状态未取消

2019-04-23 16:57 UTC, sfire commented on zh_CN/zh_CN.po
>  #, fuzzy
fuzzy状态未取消

2019-04-23 16:57 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "摄像机匹配帧 -> 选中的"
`sletection` 与 `selected` 在tooltip中改为 `选中的` ，这我不反对。但是，在菜单中，为了简洁起见，建议保留 `所选`，这个词本身也没有歧义。

2019-04-23 16:57 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "将光标吸附到选中的项"
`sletection` 与 `selected` 在tooltip中改为 `选中的` ，这我不反对。但是，在菜单中，为了简洁起见，建议保留 `所选`，这个词本身也没有歧义。

2019-04-23 16:57 UTC, sfire commented on zh_CN/zh_CN.po
>  #, fuzzy
fuzzy状态未取消

2019-04-23 16:57 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "将选中的项吸附到活动项"
`sletection` 与 `selected` 在tooltip中改为 `选中的` ，这我不反对。但是，在菜单中，为了简洁起见，建议保留 `所选`，这个词本身也没有歧义。

2019-04-23 16:57 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "外观显影"
`lookdev` 待讨论后再译，先保留一下

2019-04-23 16:57 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "切换外观显影着色"
lookdev 待讨论后再译，先保留一下

2019-04-23 16:57 UTC, sfire commented on zh_CN/zh_CN.po
> +msgstr "外观显影高动态范围成像"
lookdev 待讨论后再译，先保留一下

2019-04-23 16:57 UTC, sfire commented on zh_CN/zh_CN.po
> -"Measure distance and angles.\n"
不要改词条原文

2019-04-23 16:57 UTC, sfire commented on zh_CN/zh_CN.po
> -"• {} anywhere for new measurement.\n"
不要改词条原文

2019-04-24 09:16 UTC, millionart commented
感谢如此详细的反馈。

1. freestyle 这个词表示的是街头涂鸦那种美术风格，之所以希望翻译掉这个词，因为blender从2.8版本迎来了更多的新用户，有描边需求的时候会因为这个词的含糊而错过这个功能，找一圈教程又回到这个位置。在游戏界有代表性的同名游戏 freestyle 就是以描边涂鸦风格作为特色，而在 blender 里 freestyle 也只有描边这个功能，我认为翻译成描边风格比较合适。想了解一下翻译组对 freestyle 的含义有没有其他解释，可以再讨论。

2.选中的和所选确实区别不大，我批量调整这个词是希望翻译结果少一点书面化而以。

我很认同翻译组的严谨程度，但是对翻译进度有些异议，所以接下来我可能会在官方翻译的基础上做一些自己的翻译，因为质量和理解方面的差异（我主要求快），可能不适合主动推送，希望理解。

最后想问一下是否可以将专有名词表公开一下，方便其他翻译者贡献时不会产生类似 link 这样的差异。

感谢

2019-04-24 09:16 UTC, closed without merging

2019-04-24 10:57 UTC, sfire commented
- [Freestyle](https://docs.blender.org/manual/zh-hans/dev/render/freestyle/introduction.html#what-is-freestyle)就是跟Cycles和Eevee一样的渲染引擎名称，没有译为中文的必要。新用户想要了解的话，很容易查到资料，改中文名后反而会让人混乱。

- 菜单的名称还是尽量简洁精炼为好，tooltip里的介绍可以口语化一些。

- 关于翻译进度的问题，需要解释一下：
    1. UI的翻译是面向整个中文社区的，所以我汉化的方法一直是对照UI，实际操作去了解功能之后再翻译的。但由于个人精力有限，而且部分功能也未实际操作过，所以进度一直很慢。
    2. 我对于翻译进度也很着急，一直在社区交流群、贴吧要求社区积极参与进来，在社区期刊发稿求助。希望用到相关功能的用户能给出专业的建议和反馈，以加快进度。但是社区的很多老用户都习惯英文界面了，没有迫切的汉化需求，所以我得到的回馈少之又少。
    3. 在GitHub开这个仓库，也就是期望有用户能够参与进来协作完成汉化(但其实我并未报太大期望)。

- 你能够参与进来，提交pull request，我是非常高兴的，昨晚花了一个多小时来审核你的提交。我觉得等大家对于汉化有了默契之后，审核起来应该就没那么费事了。

- 关于专有名词的事情，我们倒是没有专门整理过，不过我觉得可以从今天开始梳理，慢慢整理一份出来。

最后，请按照审核要求重新提交。如果能再拉一两个人入坑就更好了！！^-^

2019-04-24 12:23 UTC, millionart commented
希望尽快整理专有名词表，方便其他人参与进来，避免再出现大量翻译不统一的问题。
有了名词表其他人就可以在 pull 前自查了。

或者单独开一个分支用来收录其他人的pull，由团队整理进master。

2019-04-24 12:57 UTC, sfire commented
稍后我会整理一个词典出来的。